[package]
name = "alethia-reth-block"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
alethia-reth-evm = { path = "../evm" }
alethia-reth-execution = { path = "../execution", default-features = false }
alethia-reth-forks = { path = "../forks", default-features = false }
alethia-reth-primitives = { path = "../primitives", features = ["serde"] }
alloy-consensus = { workspace = true }
alloy-eips = { workspace = true }
alloy-hardforks = { workspace = true }
alloy-primitives = { workspace = true }
eyre = { workspace = true }
reth-chainspec = { workspace = true }
reth-ethereum = { workspace = true }
reth-evm = { workspace = true }
reth-node-api = { workspace = true }
reth-node-builder = { workspace = true }
reth-primitives = { workspace = true }
reth-primitives-traits = { workspace = true }
reth-revm = { workspace = true }
reth-rpc-eth-api = { workspace = true }
reth-storage-errors = { workspace = true }
