[package]
name = "alethia-reth-block"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
path = "src/lib.rs"

[features]
default = []
rpc = ["dep:reth-rpc-eth-api"]
prover = []

[dependencies]
alethia-reth-chainspec = { path = "../chainspec" }
alethia-reth-evm = { path = "../evm" }
alethia-reth-primitives = { path = "../primitives", features = ["serde"] }
alloy-consensus = { workspace = true }
alloy-eips = { workspace = true }
alloy-evm = { workspace = true }
alloy-hardforks = { workspace = true }
alloy-primitives = { workspace = true }
alloy-rpc-types-eth = { workspace = true }
eyre = { workspace = true }
reth = { workspace = true }
reth-ethereum = { workspace = true }
reth-ethereum-forks = { workspace = true }
reth-evm = { workspace = true }
reth-evm-ethereum = { workspace = true }
reth-node-api = { workspace = true }
reth-node-builder = { workspace = true }
reth-primitives-traits = { workspace = true }
reth-provider = { workspace = true }
reth-rpc-eth-api = { workspace = true }
revm-database-interface = { workspace = true }
