[package]
name = "taiko-reth"
version = "0.1.0"
edition = "2024"
rust-version = "1.87"
license = "MIT"

[[bin]]
name = "taiko-reth"
path = "src/bin/main.rs"
required-features = ["bin"]

[lib]
name = "taiko_reth"
path = "src/lib.rs"

# Speed up compilation time for dev builds by reducing emitted debug info.
# NOTE: Debuggers may provide less useful information with this setting.
# Uncomment this section if you're using a debugger.
[profile.dev]
# https://davidlattimore.github.io/posts/2024/02/04/speeding-up-the-rust-edit-build-run-cycle.html
debug = "line-tables-only"
split-debuginfo = "unpacked"

# Speed up tests.
[profile.dev.package]
proptest.opt-level = 3
rand_chacha.opt-level = 3
rand_xorshift.opt-level = 3
unarray.opt-level = 3

# Like release, but with full debug symbols. Useful for e.g. `perf`.
[profile.debug-fast]
inherits = "release"
debug = true
lto = "thin"

[profile.maxperf]
inherits = "release"
lto = "fat"
codegen-units = 1
incremental = false

[dependencies]
# reth
reth = { git = "https://github.com/paradigmxyz/reth", package = "reth", tag = "v1.6.0", default-features = false, optional = true }
reth-consensus = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0", default-features = false }
reth-chainspec = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0", default-features = false }
reth-consensus-common = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0", default-features = false }
reth-ethereum-engine-primitives = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0", default-features = false }
reth-basic-payload-builder = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0", default-features = false }
reth-payload-primitives = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0", default-features = false }
reth-payload-builder = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0", default-features = false }
reth-trie-common = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0", default-features = false }
reth-primitives = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0", default-features = false }
reth-primitives-traits = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0", default-features = false }
reth-payload-validator = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0", default-features = false }
reth-engine-primitives = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0", default-features = false }
reth-network-api = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0", default-features = false }
reth-evm-ethereum = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0", default-features = false }
reth-ethereum = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0", default-features = false }
reth-ethereum-consensus = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0", default-features = false }
reth-ethereum-primitives = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0", default-features = false }
reth-cli-util = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0", default-features = false }
reth-evm = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0", default-features = false }
reth-storage-api = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0", default-features = false }
reth-ethereum-forks = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0", default-features = false }
reth-tracing = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0", default-features = false }
reth-transaction-pool = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0", default-features = false }
reth-revm = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0", default-features = false }
reth-tasks = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0", default-features = false }
reth-network-peers = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0", default-features = false }
reth-node-api = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0", default-features = false, optional = true }
reth-network = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0", default-features = false, optional = true }
reth-node-core = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0", default-features = false, optional = true }
reth-node-metrics = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0", default-features = false, optional = true }
reth-node-ethereum = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0", default-features = false, optional = true }
reth-node-builder = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0", default-features = false, optional = true }
reth-engine-local = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0", default-features = false, optional = true }
reth-ethereum-cli = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0", default-features = false, optional = true }
reth-db = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0", default-features = false, optional = true }
reth-rpc = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0", default-features = false, optional = true }
reth-rpc-eth-api = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0", default-features = true, optional = true }
reth-rpc-api = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0", default-features = false, optional = true }
reth-rpc-engine-api = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0", default-features = false, optional = true }
reth-rpc-eth-types = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0", default-features = false, optional = true }
reth-rpc-server-types = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0", default-features = false, optional = true }
reth-cli = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0", default-features = false, optional = true }
reth-cli-commands = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0", default-features = false, optional = true }
reth-cli-runner = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0", default-features = false, optional = true }
reth-codecs = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0", default-features = false, optional = true }
reth-db-api = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0", default-features = false, optional = true }
reth-trie-db = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0", default-features = false, optional = true }

# alloy
alloy-eips = { version = "1.0.23", default-features = false }
alloy-genesis = { version = "1.0.23", default-features = false }
alloy-consensus = { version = "1.0.23", default-features = false }
alloy-evm = { version = "0.15", default-features = false }
alloy-rpc-types-eth = { version = "1.0.23", default-features = false }
alloy-primitives = { version = "1.0.23", default-features = false }
alloy-serde = { version = "1.0.23", default-features = false }
alloy-rpc-types-txpool = { version = "1.0.23", default-features = false }
alloy-rpc-types-trace = { version = "1.0.23", default-features = false }
alloy-json-rpc = { version = "1.0.23", default-features = false }
alloy-network = { version = "1.0.23", default-features = false }
alloy-signer = { version = "1.0.23", default-features = false }
alloy-rpc-types-engine = { version = "1.0.23", default-features = false }
alloy-tx-macros = { version = "1.0.23", default-features = false }
alloy-rpc-client = { version = "1.0.23", default-features = false }
alloy-chains = { version = "0.2.5", default-features = false }
alloy-hardforks = "0.2.7"
alloy-rlp = { version = "0.3.10", default-features = false, features = [
  "core-net",
] }
alloy-sol-types = { version = "1.3.0", default-features = false }
op-alloy-flz = { version = "0.13.1", default-features = false }

# revm
revm-database-interface = { version = "7.0.1", default-features = false }

# rpc
jsonrpsee = { version = "0.25.1", default-features = false, optional = true }
jsonrpsee-core = { version = "0.25.1", default-features = false, optional = true }
jsonrpsee-server = { version = "0.25.1", default-features = false, optional = true }
jsonrpsee-http-client = { version = "0.25.1", default-features = false, optional = true }
jsonrpsee-types = { version = "0.25.1", default-features = false, optional = true }

# misc
eyre = "0.6"
arbitrary = "1.3"
clap = "4"
async-trait = "0.1.68"
parity-scale-codec = "3.2.1"
parking_lot = "0.12"
tokio-retry = "0.3"
tracing = { version = "0.1.0", default-features = false }
derive_more = { version = "2", default-features = false, features = ["full"] }
sha2 = { version = "0.10", default-features = false }
thiserror = { version = "2.0.0", default-features = false }
serde = { version = "1.0", default-features = false }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
serde_with = { version = "3", default-features = false, features = [
  "macros",
  "base64",
] }
auto_impl = "1"

[features]
default = ["serde", "bin"]
serde = ["serde/derive"]
client = []
arbitrary = ["alloy-consensus/arbitrary"]
node = [
  "net",
  "rpc",
  "dep:reth-node-api",
  "dep:reth-node-core",
  "dep:reth-node-builder",
  "dep:reth-node-metrics",
  "dep:reth-node-ethereum",
  "dep:reth-engine-local",
  "dep:reth-ethereum-cli",
  "dep:reth-cli",
  "dep:reth-cli-commands",
  "dep:reth-cli-runner",
  "dep:reth-db",
]
net = ["dep:reth-network"]
rpc = [
  "dep:reth-rpc",
  "dep:reth-rpc-api",
  "dep:reth-rpc-eth-api",
  "dep:reth-rpc-eth-types",
  "dep:reth-rpc-engine-api",
  "dep:reth-rpc-server-types",
  "dep:jsonrpsee",
  "dep:jsonrpsee-core",
  "dep:jsonrpsee-server",
  "dep:jsonrpsee-http-client",
  "dep:jsonrpsee-types",
]
db = ["dep:reth-codecs", "dep:reth-db-api", "dep:reth-trie-db"]
bin = ["node", "rpc", "net", "db", "dep:reth"]
