[package]
name = "taiko-reth"
version = "0.1.0"
edition = "2024"
rust-version = "1.87"
license = "MIT"

[[bin]]
name = "taiko-reth"
path = "src/bin/main.rs"

[lib]
name = "taiko_reth"
path = "src/lib.rs"

# Speed up compilation time for dev builds by reducing emitted debug info.
# NOTE: Debuggers may provide less useful information with this setting.
# Uncomment this section if you're using a debugger.
[profile.dev]
# https://davidlattimore.github.io/posts/2024/02/04/speeding-up-the-rust-edit-build-run-cycle.html
debug = "line-tables-only"
split-debuginfo = "unpacked"

# Speed up tests.
[profile.dev.package]
proptest.opt-level = 3
rand_chacha.opt-level = 3
rand_xorshift.opt-level = 3
unarray.opt-level = 3

# Like release, but with full debug symbols. Useful for e.g. `perf`.
[profile.debug-fast]
inherits = "release"
debug = true
lto = "thin"

[profile.maxperf]
inherits = "release"
lto = "fat"
codegen-units = 1
incremental = false

[dependencies]
# reth
reth = { git = "https://github.com/paradigmxyz/reth", package = "reth", tag = "v1.6.0" }
reth-node-ethereum = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0" }
reth-ethereum-engine-primitives = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0" }
reth-basic-payload-builder = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0" }
reth-payload-primitives = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0" }
reth-rpc-eth-types = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0" }
reth-node-api = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0" }
reth-node-builder = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0" }
reth-rpc = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0" }
reth-rpc-server-types = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0" }
reth-trie-common = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0" }
reth-db-api = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0" }
reth-provider = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0" }
reth-engine-local = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0" }
reth-primitives-traits = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0" }
reth-payload-validator = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0" }
reth-engine-primitives = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0" }
reth-rpc-engine-api = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0" }
reth-network-peers = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0" }
reth-trie-db = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0" }
reth-evm-ethereum = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0" }
reth-ethereum = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0" }
reth-ethereum-primitives = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0" }
reth-cli-util = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0" }
reth-evm = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0" }
reth-codecs = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0" }
reth-db = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0" }
reth-cli-commands = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0" }
reth-rpc-eth-api = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0" }
reth-ethereum-forks = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0" }
reth-tracing = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0" }
reth-cli = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0" }
reth-transaction-pool = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0" }
reth-revm = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0" }

# alloy
alloy-eips = { version = "1.0.23", default-features = false }
alloy-genesis = { version = "1.0.23", default-features = false }
alloy-consensus = { version = "1.0.23", default-features = false, features = [
  "arbitrary",
] }
alloy-evm = { version = "0.15", default-features = false }
alloy-rpc-types-eth = { version = "1.0.23", default-features = false }
alloy-primitives = { version = "1.0.23", default-features = false }
alloy-serde = { version = "1.0.23", default-features = false }
alloy-rpc-types-txpool = { version = "1.0.23", default-features = false }
alloy-rpc-types-trace = { version = "1.0.23", default-features = false }
alloy-json-rpc = { version = "1.0.23", default-features = false }
alloy-network = { version = "1.0.23", default-features = false }
alloy-signer = { version = "1.0.23", default-features = false }
alloy-rpc-types-engine = { version = "1.0.23", default-features = false }
alloy-tx-macros = { version = "1.0.23", default-features = false }
alloy-rpc-client = { version = "1.0.23", default-features = false }
alloy-chains = { version = "0.2.5", default-features = false }
alloy-hardforks = "0.2.7"
alloy-rlp = { version = "0.3.10", default-features = false, features = [
  "core-net",
] }
alloy-sol-types = {version = "1.3.0", default-features = false}
op-alloy-flz = { version = "0.13.1", default-features = false }

# revm
revm-database-interface = { version = "7.0.1", default-features = false }

# rpc
jsonrpsee = "0.25.1"
jsonrpsee-core = "0.25.1"
jsonrpsee-server = "0.25.1"
jsonrpsee-http-client = "0.25.1"
jsonrpsee-types = "0.25.1"

# misc
cc = "=1.2.15"
eyre = "0.6"
arbitrary = "1.3"
clap = "4"
async-trait = "0.1.68"
parity-scale-codec = "3.2.1"
parking_lot = "0.12"
tokio-retry = "0.3"
tracing = { version = "0.1.0", default-features = false }
derive_more = { version = "2", default-features = false, features = ["full"] }
sha2 = { version = "0.10", default-features = false }
thiserror = { version = "2.0.0", default-features = false }
serde = { version = "1.0", default-features = false }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
serde_with = { version = "3", default-features = false, features = [
  "macros",
  "base64",
] }
auto_impl = "1"

[features]
default = ["serde"]
serde = ["serde/derive"]
client = []
arbitrary = ["alloy-consensus/arbitrary"]
