[package]
name = "alethia-reth-chainspec"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
path = "src/lib.rs"

[features]
default = []
serde = ["alethia-reth-chainspec-core/serde"]

[dependencies]
alethia-reth-chainspec-core = { path = "../chainspec-core", default-features = false }
alloy-hardforks = { workspace = true }
eyre = { workspace = true }
reth-chainspec = { workspace = true }
reth-cli = { workspace = true }
reth-revm = { workspace = true }
rayon = { workspace = true }
